import json
from krita_comfy.prompt import PromptBase, PromptResponse, get_members


def test_load(base: PromptBase, resp: PromptResponse):
    keys = get_members(base)
    result: bool = True
    for k in keys:
        if not getattr(base, k) == getattr(resp, k):
            print(k, "is", getattr(base, k) , "should be", getattr(resp, k))
            result = False
    return result


def test_PromptResponse_from_history_json(workflow_str: str, expected_str: str):
    workflow = json.loads(workflow_str)
    expected = json.loads(expected_str)
    result = PromptResponse.from_history_json(history=workflow)
    result_json = result.to_base_prompt_json()
    result_from_json = PromptResponse.from_json(result_json)
    compare_json: set = set(json.loads(result_json).items()) ^ set(expected.items())
    if len(compare_json) > 0:
        print("Fail (Actual, Expected)", compare_json)
    elif not test_load(result_from_json, result):
        print("Fail")
    else:
        print("Pass")


def main():
    tests = [
        # dpmpp_sde, karras, steps:20, cfg 8, denoise 0.75
        ["test_txt2img_hires" , [
            '''{"prompt": [73, "b1f81b10-5bee-485a-8b91-22152fda15c9", {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "dir/model_v10.safetensors"}}, "VAEDecode": {"class_type": "VAEDecode", "inputs": {"samples": ["KSampler_upscale", 0], "vae": ["VAELoader", 0]}}, "SaveImage": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ComfyUI", "images": ["VAEDecode", 0]}}, "ClipSetLastLayer": {"class_type": "CLIPSetLastLayer", "inputs": {"stop_at_clip_layer": -2, "clip": ["4", 1]}}, "VAELoader": {"class_type": "VAELoader", "inputs": {"vae_name": "blessed2.vae.pt"}}, "3": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 1.0, "model": ["4", 0], "latent_image": ["5", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 587908720942082704, "steps": 10}}, "5": {"class_type": "EmptyLatentImage", "inputs": {"batch_size": 1, "height": 768, "width": 1280}}, "6": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "Pos"}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "neg"}}, "VAEDecode_upscale": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["VAELoader", 0]}}, "UpscaleModelLoader": {"class_type": "UpscaleModelLoader", "inputs": {"model_name": "RealESRGAN_x4plus_anime_6B.pth"}}, "ImageUpscaleWithModel": {"class_type": "ImageUpscaleWithModel", "inputs": {"upscale_model": ["UpscaleModelLoader", 0], "image": ["VAEDecode_upscale", 0]}}, "ImageScale": {"class_type": "ImageScale", "inputs": {"upscale_method": "bilinear", "width": 1920, "height": 1080, "crop": "disabled", "image": ["ImageUpscaleWithModel", 0]}}, "VAEEncode_upscale": {"class_type": "VAEEncode", "inputs": {"pixels": ["ImageScale", 0], "vae": ["VAELoader", 0]}}, "KSampler_upscale": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.7500000000000001, "model": ["4", 0], "latent_image": ["VAEEncode_upscale", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 587908720942082704, "steps": 10}}}, {"client_id": "bc6d4161-d678-4dcc-a23f-35ff66335c54"}, ["SaveImage"]], "outputs": {"SaveImage": {"images": [{"filename": "ComfyUI_02824_.png", "subfolder": "", "type": "output"}]}}}'''
            , '''{"mode": "empty", "sd_model": "dir/model_v10.safetensors", "clip_skip": -2, "seed": 587908720942082704, "pos_prompt": "Pos", "neg_prompt": "neg", "sampler": "dpmpp_sde", "scheduler": "karras", "steps": 20, "cfg": 8.0, "denoise": 0.75}'''
        ]],
        ["test_txt2img", [
            '''{"prompt": [75, "0bf2ebe3-75ee-4e2a-a36a-df9e69a8eb9e", {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "dir/model_v10.safetensors"}}, "VAEDecode": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["VAELoader", 0]}}, "SaveImage": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ComfyUI", "images": ["VAEDecode", 0]}}, "ClipSetLastLayer": {"class_type": "CLIPSetLastLayer", "inputs": {"stop_at_clip_layer": -2, "clip": ["4", 1]}}, "VAELoader": {"class_type": "VAELoader", "inputs": {"vae_name": "blessed2.vae.pt"}}, "3": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 1.0, "model": ["4", 0], "latent_image": ["5", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 11958850938108435757, "steps": 20}}, "5": {"class_type": "EmptyLatentImage", "inputs": {"batch_size": 1, "height": 768, "width": 1280}}, "6": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "Pos"}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "neg"}}}, {"client_id": "11467e60-3be8-458f-a8a0-c0dd47d05233"}, ["SaveImage"]], "outputs": {"SaveImage": {"images": [{"filename": "ComfyUI_02826_.png", "subfolder": "", "type": "output"}]}}}'''
            , '''{"mode": "empty", "sd_model": "dir/model_v10.safetensors", "clip_skip": -2, "seed": 11958850938108435757, "pos_prompt": "Pos", "neg_prompt": "neg", "sampler": "dpmpp_sde", "scheduler": "karras", "steps": 20, "cfg": 8.0, "denoise": null}'''
        ]],
        # dpmpp_sde, karras, steps:20, cfg 8, denoise 0.65
        ["test_img2img_hires", [
            '''{"prompt": [78, "6e32a7bf-8ded-4e72-803e-4044a580f2a9", {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "dir/model_v10.safetensors"}}, "VAEDecode": {"class_type": "VAEDecode", "inputs": {"samples": ["KSampler_upscale", 0], "vae": ["VAELoader", 0]}}, "SaveImage": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ComfyUI", "images": ["VAEDecode", 0]}}, "ClipSetLastLayer": {"class_type": "CLIPSetLastLayer", "inputs": {"stop_at_clip_layer": -2, "clip": ["4", 1]}}, "VAELoader": {"class_type": "VAELoader", "inputs": {"vae_name": "blessed2.vae.pt"}}, "3": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.65, "model": ["4", 0], "latent_image": ["VAEEncode", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 7259513998170936073, "steps": 10}}, "LoadBase64Image": {"class_type": "LoadBase64Image", "inputs": {"image": "__snip__"}}, "VAEEncode": {"class_type": "VAEEncode", "inputs": {"pixels": ["LoadBase64Image", 0], "vae": ["VAELoader", 0]}}, "6": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "Pos"}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "neg"}}, "VAEDecode_upscale": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["VAELoader", 0]}}, "UpscaleModelLoader": {"class_type": "UpscaleModelLoader", "inputs": {"model_name": "RealESRGAN_x4plus_anime_6B.pth"}}, "ImageUpscaleWithModel": {"class_type": "ImageUpscaleWithModel", "inputs": {"upscale_model": ["UpscaleModelLoader", 0], "image": "__snip__"}}, "ImageScale": {"class_type": "ImageScale", "inputs": {"upscale_method": "bilinear", "width": 1920, "height": 1080, "crop": "disabled", "image": "__snip__"}}, "VAEEncode_upscale": {"class_type": "VAEEncode", "inputs": {"pixels": ["ImageScale", 0], "vae": ["VAELoader", 0]}}, "KSampler_upscale": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.65, "model": ["4", 0], "latent_image": ["VAEEncode_upscale", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 7259513998170936073, "steps": 10}}}, {"client_id": "0310daf5-3c7a-4d48-9741-7fe37d200c25"}, ["SaveImage"]], "outputs": {"SaveImage": {"images": [{"filename": "ComfyUI_02829_.png", "subfolder": "", "type": "output"}]}}}'''
            , '''{"mode": "empty", "sd_model": "dir/model_v10.safetensors", "clip_skip": -2, "seed": 7259513998170936073, "pos_prompt": "Pos", "neg_prompt": "neg", "sampler": "dpmpp_sde", "scheduler": "karras", "steps": 20, "cfg": 8.0, "denoise": 0.65}'''
        ]],
        ["test_img2img", [
            '''{"prompt": [77, "2da4024d-03b2-417c-a3c6-cad8c07e9750", {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "dir/model_v10.safetensors"}}, "VAEDecode": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["VAELoader", 0]}}, "SaveImage": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ComfyUI", "images": ["VAEDecode", 0]}}, "ClipSetLastLayer": {"class_type": "CLIPSetLastLayer", "inputs": {"stop_at_clip_layer": -2, "clip": ["4", 1]}}, "VAELoader": {"class_type": "VAELoader", "inputs": {"vae_name": "blessed2.vae.pt"}}, "3": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.65, "model": ["4", 0], "latent_image": ["VAEEncode", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 4257281857213919793, "steps": 20}}, "LoadBase64Image": {"class_type": "LoadBase64Image", "inputs": {"image": "__snip__"}}, "VAEEncode": {"class_type": "VAEEncode", "inputs": {"pixels": ["LoadBase64Image", 0], "vae": ["VAELoader", 0]}}, "6": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "Pos"}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "neg"}}}, {"client_id": "8fe8b72e-5c8a-4d45-9f2e-a7a0c11f0ef1"}, ["SaveImage"]], "outputs": {"SaveImage": {"images": [{"filename": "ComfyUI_02828_.png", "subfolder": "", "type": "output"}]}}}'''
            ,'''{"mode": "empty", "sd_model": "dir/model_v10.safetensors", "clip_skip": -2, "seed": 4257281857213919793, "pos_prompt": "Pos", "neg_prompt": "neg", "sampler": "dpmpp_sde", "scheduler": "karras", "steps": 20, "cfg": 8.0, "denoise": 0.65}'''
        ]],
        ["test_inpaint_hires", [
            '''{"prompt": [82, "e864444b-7890-4d21-88c7-018db4194e3c", {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "dir/model_v10.safetensors"}}, "VAEDecode": {"class_type": "VAEDecode", "inputs": {"samples": ["KSampler_upscale", 0], "vae": ["VAELoader", 0]}}, "SaveImage": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ComfyUI", "images": ["VAEDecode", 0]}}, "ClipSetLastLayer": {"class_type": "CLIPSetLastLayer", "inputs": {"stop_at_clip_layer": -2, "clip": ["4", 1]}}, "VAELoader": {"class_type": "VAELoader", "inputs": {"vae_name": "blessed2.vae.pt"}}, "SetLatentNoiseMask": {"class_type": "SetLatentNoiseMask", "inputs": {"samples": ["VAEEncode", 0], "mask": ["LoadBase64ImageMask", 0]}}, "3": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.6500000000000001, "model": ["4", 0], "latent_image": ["SetLatentNoiseMask", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 15996700938809001900, "steps": 10}}, "LoadBase64Image": {"class_type": "LoadBase64Image", "inputs": {"image": "__snip__"}}, "LoadBase64ImageMask": {"class_type": "LoadBase64ImageMask", "inputs": {"image": "__snip__", "channel": "alpha"}}, "VAEEncode": {"class_type": "VAEEncode", "inputs": {"pixels": ["LoadBase64Image", 0], "vae": ["VAELoader", 0]}}, "6": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "Pos"}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "neg"}}, "VAEDecode_upscale": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["VAELoader", 0]}}, "UpscaleModelLoader": {"class_type": "UpscaleModelLoader", "inputs": {"model_name": "RealESRGAN_x4plus_anime_6B.pth"}}, "ImageUpscaleWithModel": {"class_type": "ImageUpscaleWithModel", "inputs": {"upscale_model": ["UpscaleModelLoader", 0], "image": "__snip__"}}, "ImageScale": {"class_type": "ImageScale", "inputs": {"upscale_method": "bilinear", "width": 1920, "height": 1080, "crop": "disabled", "image": "__snip__"}}, "VAEEncode_upscale": {"class_type": "VAEEncode", "inputs": {"pixels": ["ImageScale", 0], "vae": ["VAELoader", 0]}}, "KSampler_upscale": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.6500000000000001, "model": ["4", 0], "latent_image": ["SetLatentNoiseMask_upscale", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 15996700938809001900, "steps": 10}}, "SetLatentNoiseMask_upscale": {"class_type": "SetLatentNoiseMask", "inputs": {"samples": ["VAEEncode_upscale", 0], "mask": ["LoadBase64ImageMask", 0]}}}, {"client_id": "29528189-2122-48f4-b68e-7c3d5bf863cf"}, ["SaveImage"]], "outputs": {"SaveImage": {"images": [{"filename": "ComfyUI_02833_.png", "subfolder": "", "type": "output"}]}}}'''
            ,
            '''{"mode": "empty", "sd_model": "dir/model_v10.safetensors", "clip_skip": -2, "seed": 15996700938809001900, "pos_prompt": "Pos", "neg_prompt": "neg", "sampler": "dpmpp_sde", "scheduler": "karras", "steps": 20, "cfg": 8.0, "denoise": 0.65}'''
        ]],
        ["test_inpaint", [
            '''{"prompt": [81, "8387559c-80b4-4508-b7b4-6ea92ac699b6", {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "dir/model_v10.safetensors"}}, "VAEDecode": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["VAELoader", 0]}}, "SaveImage": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ComfyUI", "images": ["VAEDecode", 0]}}, "ClipSetLastLayer": {"class_type": "CLIPSetLastLayer", "inputs": {"stop_at_clip_layer": -2, "clip": ["4", 1]}}, "VAELoader": {"class_type": "VAELoader", "inputs": {"vae_name": "blessed2.vae.pt"}}, "SetLatentNoiseMask": {"class_type": "SetLatentNoiseMask", "inputs": {"samples": ["VAEEncode", 0], "mask": ["LoadBase64ImageMask", 0]}}, "3": {"class_type": "KSampler", "inputs": {"cfg": 8.0, "denoise": 0.6500000000000001, "model": ["4", 0], "latent_image": ["SetLatentNoiseMask", 0], "negative": ["7", 0], "positive": ["6", 0], "sampler_name": "dpmpp_sde", "scheduler": "karras", "seed": 12255115070878758213, "steps": 20}}, "LoadBase64Image": {"class_type": "LoadBase64Image", "inputs": {"image": "__snip__"}}, "LoadBase64ImageMask": {"class_type": "LoadBase64ImageMask", "inputs": {"image": "__snip__", "channel": "alpha"}}, "VAEEncode": {"class_type": "VAEEncode", "inputs": {"pixels": ["LoadBase64Image", 0], "vae": ["VAELoader", 0]}}, "6": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "Pos"}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["ClipSetLastLayer", 0], "text": "neg"}}}, {"client_id": "29528189-2122-48f4-b68e-7c3d5bf863cf"}, ["SaveImage"]], "outputs": {"SaveImage": {"images": [{"filename": "ComfyUI_02832_.png", "subfolder": "", "type": "output"}]}}}'''
            ,'''{"mode": "empty", "sd_model": "dir/model_v10.safetensors", "clip_skip": -2, "seed": 12255115070878758213, "pos_prompt": "Pos", "neg_prompt": "neg", "sampler": "dpmpp_sde", "scheduler": "karras", "steps": 20, "cfg": 8.0, "denoise": 0.65}'''
        ]],
    ]

    for test in tests:
        print(test[0])
        test_PromptResponse_from_history_json(test[1][0], test[1][1])


if __name__ == '__main__':
    main()
